import { type NextPage } from "next";
import Head from "next/head";

import { Navbar } from "~/components/Navbar";
import TodoList from "~/components/TodoList";
import { type RouterOutputs } from "~/utils/api";
import { useState } from "react";

import { TodoListContext } from "~/context/todoListContext";
import CreateTodo from "~/components/CreateTodo";
import Todos from "~/components/Todos";

type TodoList = RouterOutputs["todoList"]["getAll"][0];

const Home: NextPage = () => {
  const [selectedTodoList, setSelectedTodoList] = useState<TodoList | null>(
    null
  );

  return (
    <TodoListContext.Provider value={(selectedTodoList, setSelectedTodoList)}>
      <Head>
        <title>WEBB-TODO</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="min-h-screen gap-10 bg-gradient-to-b from-[#020005] to-[#15162c] p-10 md:grid md:grid-cols-5">
        <div className="mt-20 flex flex-col gap-10 md:col-span-2">
          <TodoList />
        </div>
        {selectedTodoList &&
        selectedTodoList.id !== "" &&
        selectedTodoList.id !== undefined ? (
          <div className="mt-20 flex flex-col md:col-span-3 ">
            <Todos />
            <div className="divider"></div>
            <CreateTodo />
          </div>
        ) : (
          <div></div>
        )}
      </main>
    </TodoListContext.Provider>
  );
};

export default Home;
